// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvyMUFz_9USCF7Ro1ljhMJaNKMoYRilw',
    appId: '1:922986833753:web:08b05598cef659dd344e48',
    messagingSenderId: '922986833753',
    projectId: 'foodwaste-kh2026-yx-ca35f',
    authDomain: 'foodwaste-kh2026-yx-ca35f.firebaseapp.com',
    storageBucket: 'foodwaste-kh2026-yx-ca35f.firebasestorage.app',
    measurementId: 'G-J5EHPJPYSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4flLBT2vjTsrEzmq13JvMh3rJjFftOYg',
    appId: '1:922986833753:android:cb0a8a886ee843ec344e48',
    messagingSenderId: '922986833753',
    projectId: 'foodwaste-kh2026-yx-ca35f',
    storageBucket: 'foodwaste-kh2026-yx-ca35f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJkYeC8xj-4wQavef9ZrgfIEO78gyhmzY',
    appId: '1:922986833753:ios:bda1653206bfb8ef344e48',
    messagingSenderId: '922986833753',
    projectId: 'foodwaste-kh2026-yx-ca35f',
    storageBucket: 'foodwaste-kh2026-yx-ca35f.firebasestorage.app',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJkYeC8xj-4wQavef9ZrgfIEO78gyhmzY',
    appId: '1:922986833753:ios:bda1653206bfb8ef344e48',
    messagingSenderId: '922986833753',
    projectId: 'foodwaste-kh2026-yx-ca35f',
    storageBucket: 'foodwaste-kh2026-yx-ca35f.firebasestorage.app',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYvyMUFz_9USCF7Ro1ljhMJaNKMoYRilw',
    appId: '1:922986833753:web:1985432bf5414247344e48',
    messagingSenderId: '922986833753',
    projectId: 'foodwaste-kh2026-yx-ca35f',
    authDomain: 'foodwaste-kh2026-yx-ca35f.firebaseapp.com',
    storageBucket: 'foodwaste-kh2026-yx-ca35f.firebasestorage.app',
    measurementId: 'G-EK6J0BFJE8',
  );

}